# Generated by Django 3.0.3 on 2020-05-04 16:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.CharField(default='', max_length=10)),
                ('id_bor1', models.CharField(blank=True, default='', max_length=10)),
                ('create1', models.DateTimeField(default=datetime.datetime(2020, 5, 4, 23, 3, 4, 387783, tzinfo=utc))),
                ('id_bor2', models.CharField(blank=True, default='', max_length=10)),
                ('create2', models.DateTimeField(default=datetime.datetime(2020, 5, 4, 23, 3, 4, 387783, tzinfo=utc))),
                ('id_bor3', models.CharField(blank=True, default='', max_length=10)),
                ('create3', models.DateTimeField(default=datetime.datetime(2020, 5, 4, 23, 3, 4, 387783, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Category_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Check_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bor', models.CharField(blank=True, default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('opinion', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='DocGia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_DG', models.CharField(default='', max_length=8)),
                ('ten_DG', models.CharField(max_length=100)),
                ('gioitinh', models.IntegerField(choices=[(0, 'Nữ'), (1, 'Nam')], default=0)),
                ('email_DG', models.EmailField(max_length=200)),
                ('CMND', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('image_user', models.ImageField(blank=True, null=True, upload_to='image_user/')),
                ('money_user', models.IntegerField(blank=True, default=0)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_book', models.CharField(default='', max_length=10)),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('image_book', models.ImageField(blank=True, null=True, upload_to='image_book/')),
                ('author', models.CharField(blank=True, default='', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('new', models.BooleanField(blank=True, default=False)),
                ('rate', models.IntegerField(blank=True, default=0)),
                ('vote', models.IntegerField(blank=True, default=0)),
                ('ave_rate', models.IntegerField(blank=True, default=0)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smart_Library.Category_Book')),
            ],
        ),
    ]
