# Generated by Django 3.0.3 on 2020-05-24 14:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Smart_Library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id_book',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='cart',
            name='create1',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 21, 15, 24, 105806, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='create2',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 21, 15, 24, 105806, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='create3',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 21, 15, 24, 105806, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='id_bor1',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='cart',
            name='id_bor2',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='cart',
            name='id_bor3',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='check_book',
            name='id_bor',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
    ]
