# Generated by Django 3.0.3 on 2020-05-25 12:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Smart_Library', '0002_auto_20200524_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docgia',
            name='gioitinh',
        ),
        migrations.AlterField(
            model_name='cart',
            name='create1',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 19, 29, 0, 298702, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='create2',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 19, 29, 0, 298702, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='create3',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 19, 29, 0, 298702, tzinfo=utc)),
        ),
    ]
