# Generated by Django 3.0.3 on 2020-05-25 12:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Smart_Library', '0003_auto_20200525_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='create1',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 19, 44, 35, 758898, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='create2',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 19, 44, 35, 758898, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='create3',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 19, 44, 35, 758898, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='docgia',
            name='money_user',
            field=models.IntegerField(blank=True, default=10000),
        ),
    ]
