# Generated by Django 3.0.3 on 2020-05-27 14:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Smart_Library', '0004_auto_20200525_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sl',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='create1',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 21, 37, 25, 418902, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='create2',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 21, 37, 25, 419900, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='create3',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 21, 37, 25, 419900, tzinfo=utc)),
        ),
    ]
