# Generated by Django 3.0.3 on 2020-06-08 13:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Smart_Library', '0005_auto_20200527_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='dup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='create1',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 20, 33, 7, 21202, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='create2',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 20, 33, 7, 21202, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='create3',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 20, 33, 7, 21202, tzinfo=utc)),
        ),
    ]
