# Generated by Django 3.0.3 on 2020-06-13 14:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Smart_Library', '0007_auto_20200608_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='ID_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Book', models.CharField(blank=True, default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ID_DocGia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Docgia', models.CharField(blank=True, default='', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='create1',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 13, 21, 38, 37, 68006, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='create2',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 13, 21, 38, 37, 68006, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='create3',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 13, 21, 38, 37, 68006, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='docgia',
            name='id_DG',
            field=models.CharField(default='', max_length=10),
        ),
    ]
